version: "2"

linters:
  enable:
    - errcheck # проверка необработанных ошибок
    - gosimple # упрощение кода
    - govet # стандартные проверки go vet
    - ineffassign # неиспользуемые присваивания
    - staticcheck # огромный набор проверок на логику
    - unused # поиск неиспользуемого кода
    - revive # современная замена golint
    - goimports # проверка порядка импортов
